#!/bin/sh

commandToExecute="${@:1}"

while read -p "Really do ⇛ $commandToExecute ⇚ ? " -n1 -r; do
    printf '\n'

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        $commandToExecute >&2
        exit 0
    elif [[ $REPLY =~ ^[Nn]$ ]]; then
        exit 1
    else
        printf 'Please press N or Y.\n'
    fi
done
