#!/bin/bash

branchToCreate="$1"
baseBranch="$2"

if [[ -z $branchToCreate ]]; then
    printf 'Creates a new branch from base branch (default: "develop").\n'
    printf 'Usage:\n'
    printf '  git new NEW_BRANCH [BASE_BRANCH]\n\n'
    exit
fi

if [[ -z $baseBranch ]]; then
    baseBranch='develop'
fi

confirm git checkout $baseBranch
gitpull
confirm git checkout -b $branchToCreate
