#!/bin/bash

initialBranch=$(git rev-parse --abbrev-ref HEAD);

baseBranch="$1";
if [[ -z $baseBranch ]]; then
    baseBranch='master'
    # Use 'develop' if exists
    if [[ ! -z $(git branch --list | grep 'develop') ]]; then
        baseBranch='develop'
    fi
fi


shouldAskForStash=false
if [[ ! $(git status) == *"nothing to commit"* ]]; then
    shouldAskForStash=true
fi

didConfirmStash=false
if [ $shouldAskForStash == true ]; then
    confirm git stash
    confirmExitStatus=$?
    if [ $confirmExitStatus == 0 ]; then
        didConfirmStash=true
    fi
fi

confirm git checkout $baseBranch
confirm git pull origin $baseBranch
confirm git checkout $initialBranch
confirm git rebase $baseBranch

if [ $didConfirmStash == true ]; then
    confirm git stash apply;
fi
