#!/bin/bash

initialBranch=$(git rev-parse --abbrev-ref HEAD);

baseBranch="$1";
if [[ -z $baseBranch ]]; then
    baseBranch='develop';
fi

git refresh $baseBranch
confirm git rebase -i $baseBranch
confirm git push --force origin $initialBranch
confirm hub pull-request