#!/bin/sh

git add -A

message=$(curl -s whatthecommit.com/index.txt)
#echo "$message"
git commit -m "$message"

currentBranchName=$(git rev-parse --abbrev-ref HEAD)
git push origin "${currentBranchName}"
