#!/bin/sh

currentRepoHasSubmodules=false
if [[ $(git submodule) ]]; then
    currentRepoHasSubmodules=true
fi


if [ $currentRepoHasSubmodules = true ]; then
    confirm git pull --recurse-submodules origin $(git rev-parse --abbrev-ref HEAD)
    #confirm git submodule update --recursive
else
    confirm git pull origin $(git rev-parse --abbrev-ref HEAD)
fi
