#!/bin/sh

currentRepoHasSubmodules=false
if [[ $(git submodule) ]]; then
    currentRepoHasSubmodules=true
fi


confirm git pull --tags origin $(git rev-parse --abbrev-ref HEAD)

if [ $currentRepoHasSubmodules = true ]; then
    confirm git submodule update --init --recursive
fi
