#!/bin/sh

Yellow='\033[1;33m'
LightBlue='\033[1;34m'
RESET='\033[0m'

printTitle() {
    title="$1"
    printf "\n${Yellow}${title}\n--------------------${RESET}\n"
}

# Mode
mode="$1"
validModes=('outdated','update')

# Check if mode is in validModes array
if [[ ! "${validModes[@]}" =~ "${mode}" ]]; then
    printTitle "Usage"
    printf "  package outdated   Show outdated packages\n"
    printf "  package update     Update all outdated packages\n"
    printf "\n\n"
fi





# Title
if [[ $mode = 'outdated' ]]; then
    printf 'Showing outdated packages...\n'
elif [[ $mode = 'update' ]]; then
    printf 'Updating all packages...\n'
fi


# Brew
printTitle 'Brew'
if [[ $mode = 'outdated' ]]; then
    brew outdated
elif [[ $mode = 'update' ]]; then
    brew update
    brew upgrade
fi


# Gem
printTitle 'Gems'
if [[ $mode = 'outdated' ]]; then
    gem outdated
elif [[ $mode = 'update' ]]; then
    sudo gem update
fi


# # Pod
# printTitle 'Pods'
# if [[ $mode = 'outdated' ]]; then
#     pod outdated
# fi


# Pip
printTitle 'Pip'
if [[ $mode = 'outdated' ]]; then
    pip3 list --outdated
elif [[ $mode = 'update' ]]; then
    pip3 list --outdated --format=freeze \
    | grep -v '^\-e' | cut -d= -f1 \
    | xargs -I _ pip3 install --upgrade _
fi
